<?php

# // This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'b53968a23b9707924db0ab1802f92b81ea3f5222e54247a37bbba6075ccde672',
  'APP_SHARE_DIR' => 'var/share',
  'DEFAULT_URI' => 'http://localhost',
  'DATABASE_URL' => 'postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=16&charset=utf8',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
